import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

dataset = pd.read_csv('salary_data.csv')
dataset.head()
X = dataset.iloc[:, :-1].values 
y = dataset.iloc[:, -1].values   




from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=1/3,random_state=0)
from sklearn.linear_model import LinearRegression 

regressor = LinearRegression()
regressor.fit(X_train,y_train) 
print("coefficient =",regressor.coef_)
print("Intercept = ",regressor.intercept_)
y_pred = regressor.predict(X_test)
print("y_pred=",y_pred)
print("y_test=",y_test)
plt.scatter(X_train, y_train, color='red')
plt.plot(X_train, regressor.predict(X_train), color='blue') 
plt.show() 
plt.scatter(X_test, y_test, color='red')
plt.plot(X_train, regressor.predict(X_train), color='blue')
plt.ylabel("Salaries")
plt.show()


