# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HVAvfAlhjd29QoGbLpnYhQx6Ic98FAsR

# visualizing a Normal (Gaussian) Distribution using Python.
"""

from scipy.stats import norm
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt

"""**scipy.stats.norm: Used for working with normal distributions.
numpy: For efficient numerical operations.
seaborn: For creating clean and aesthetically pleasing plots.
matplotlib.pyplot: For basic plotting and customization.**
"""

data= np.arange(1,10, 0.01)

"""**Generates values from 1 to 10 in steps of 0.01 using np.arange().
This forms the x-axis for the plot.**
"""

pdf = norm.pdf(data , loc=5.3,scale=1)

"""**norm.pdf() calculates the Probability Density Function (PDF) of a normal distribution. loc=5.3 is the mean (center of the curve). scale=1 is the standard deviation (spread of the curve). **"""

sb.set_style('whitegrid')

"""**Applies a white grid background using Seaborn for better visualization.**"""

sb.lineplot(x=data, y=pdf, color='black')
plt.xlabel('Heights')
plt.ylabel('Probability Density')
plt.show()

"""**Plots the PDF curve using sb.lineplot() with a black color.t**"""