# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e5SttvfJg1AgBwBpB5TNTIam2JSzIUse
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

"""**numpy is used for mathematical operations.
matplotlib.pyplot is used for plotting graphs.t**
"""

x=np.linspace(1,50,200)

"""**np.linspace() generates 200 evenly spaced values between 1 and 50.**"""

mean = np.mean(x)
sd = np.std(x)

""" **np.mean() calculates the average (mean).
np.std() calculates the standard deviation (spread of data).**
"""

def normal_dist(x, mean, sd):
    return (1 / (np.sqrt(2 * np.pi) * sd)) * np.exp(-0.5 * ((x - mean) / sd) ** 2)

"""**This function calculates the Probability Density Function (PDF) of a normal distribution using the standard formula.**"""

pdf = normal_dist(x,mean,sd)

"""**The function returns the PDF values for the given data points.**"""

plt.plot(x, pdf, color='red')
plt.xlabel('Data points')
plt.ylabel('Probability Density')
plt.show()