# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WRsPn9PQlYPDDJ4KQOOomcnPdc5TVHs6

# **analyzing and visualizing correlations between Experience, Salary, and Age**
"""

import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt
import pandas as pd

experience = [1, 3, 4, 5, 6, 7, 10, 11, 12, 15, 20, 25, 28, 30, 35]
salary = [20000, 30000, 40000, 45000, 55000, 60000, 80000, 100000,
          130000, 150000, 200000, 230000, 250000, 300000, 400000]
age = [20, 30, 36, 40, 28, 40, 50, 54, 49, 47, 45, 39, 29, 40, 38]

"""**experience, salary, and age represent sample data points.**"""

corr_exp_sal = stats.pearsonr(experience, salary)[0]
print(f"The r value (Experience vs Salary) is: {corr_exp_sal}")

"""**stats.pearsonr() computes the Pearson correlation coefficient, which measures the strength and direction of the linear relationship.**"""

print("Relation:", "Positive Strong" if corr_exp_sal >= 0.7 else
                     "Negative Strong" if corr_exp_sal <= -0.7 else "No Relation")

"""**Based on the correlation coefficient (r value), it categorizes the relationship as Positive Strong, Negative Strong, or No Relation.**"""

df = pd.DataFrame({'Experience': experience, 'Salary': salary, 'Age': age})
corr_exp_age = df['Experience'].corr(df['Age'])
print(f"The r value (Experience vs Age) is: {corr_exp_age}")

"""**A DataFrame is created using pandas, and the correlation between Experience and Age is calculated using .corr().**"""

plt.figure(figsize=(10, 5))

"""**Sets the figure size for better visualization.**"""

plt.subplot(1, 2, 1)
plt.scatter(experience, salary, c="blue")
plt.xlabel("Experience")
plt.ylabel("Salary")
plt.title("Experience vs Salary")

plt.subplot(1, 2, 2)
plt.scatter(df['Experience'], df['Age'], c="red")
plt.xlabel("Experience")
plt.ylabel("Age")
plt.title("Experience vs Age")
plt.tight_layout()
plt.show()

"""**A scatter plot is created using blue dots to visualize the relationship between experience and salary.**

**plt.tight_layout() adjusts the plots to prevent overlap, and plt.show() renders the plots.t**
"""