# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uBIhpjR4xU1cr0OcrGFJ3-AAqO1swoP_

# **visualizing and analyzing a Normal (Gaussian) Distribution**
"""

from scipy.stats import norm
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt

data = np.arange(1, 10, 0.01)
pdf = norm.pdf(data, loc=5.3, scale=1)

"""**np.arange() creates data points from 1 to 10 with an interval of 0.01.
norm.pdf() calculates the Probability Density Function (PDF) for a normal distribution with a mean of 5.3 and standard deviation of 1.
t**
"""

prob_1 = norm(loc=5.3, scale=1).cdf(4.5)

"""**norm.cdf() computes the Cumulative Distribution Function (CDF), representing the probability of values below 4.5 ft.**"""

prob_2 = norm(loc=5.3, scale=1).cdf(6.5) - prob_1

"""**The probability of a person’s height being between 4.5 ft and 6.5 ft is calculated using the difference between the two CDF values.**"""

prob_3 = 1 - norm(loc=5.3, scale=1).cdf(6.5)

"""**The probability of a height above 6.5 ft is calculated by subtracting the CDF from 1.**"""

print(prob_1, prob_2, prob_3)

"""**Displays the calculated probabilities.**"""

sb.set_style('whitegrid')
sb.lineplot(x=data, y=pdf, color='black')
plt.axvline(4.5, color='blue', linestyle='--', label='4.5 ft')
plt.axvline(6.5, color='green', linestyle='--', label='6.5 ft')
plt.xlabel('Heights')
plt.ylabel('Probability Density')
plt.legend()
plt.show()

"""**Sets a clean white grid background and plots the PDF using Seaborn.**

**plt.axvline() adds dashed vertical lines to mark the heights 4.5 ft and 6.5 ft.**
"""