# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rvYiVTQJUZEACMOfVJvNs1rkcRMmZR5b

# ** Simple Linear Regression**
"""

import numpy as np
import matplotlib.pyplot as plt

def estimate_coef(x, y):
  n = np.size(x)
  m_x, m_y = np.mean(x), np.mean(y)
  b_1 = (np.sum(y*x) - n*m_y*m_x) / (np.sum(x*x) - n*m_x*m_x)
  b_0 = m_y - b_1*m_x
  return b_0, b_1

"""**plt.scatter() creates a scatter plot of the actual data points.
color="m" → Plot the points in magenta.
marker="o" → Use circle markers.
s=30 → Set marker size to 30 pixels.**
"""

def plot_regression_line(x, y, b):
  plt.scatter(x, y, color="m", marker="o", s=30)
  plt.plot(x, b[0] + b[1]*x, color="g")
  plt.xlabel('x')
  plt.ylabel('y')
  plt.show()

"""**plt.plot() draws the regression line using the equation:
        y= b0 +b1.x
b[0] → Intercept (b₀)
b[1] → Slope (b₁)
color="g" → Line color is green.**
"""

x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
y = np.array([1, 3, 5, 7, 8, 9, 10, 8, 10, 12])

"""**x:Independent variable (e.g., years of experience).
y: Dependent variable (e.g., salary).**
"""

b = estimate_coef(x, y)

"""**Calls the estimate_coef() function to get the slope and intercept.**"""

print(f"Estimated coefficients: a = {b[0]:.3f}, b = {b[1]:.3f}")

"""**Prints the intercept (a) and slope (b) with three decimal places.**"""

print(f"Least square regression equation: y = {b[0]:.3f} + {b[1]:.3f}x")

"""**Displays the linear equation in the form
    y=b0 + b1.x **bold text**

"""

plot_regression_line(x, y, b)

"""**Visualizes the actual data points and the predicted regression line.**"""