# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/195tvz_whSPLfjXbOm2NxL-TPIOzWmZg8

# creating dataframe
"""

import pandas as pd
data = [['name1', 21, 'name1@gmail.com', 1234567891], ['name2', 26, 'name2@gmail.com', 1234567892]]
df = pd.DataFrame(data, columns=['NAME', 'AGE', 'EMAIL ID', 'PHONENUMBER'], index=[1, 2])
print(df)

"""# creating df using dictionary"""

import pandas as pd
data={'name':['noufal','yasar','saban','mirun'],'Age':[20,30,35,29]}
df=pd.DataFrame(data)
print(df)

"""# Creating dataframe from a series"""

import pandas as pd
data={'one':pd.Series([10,20,30,40],index=[1,2,3,4]),
      'two':pd.Series([50,60,70,80],index=[1,2,3,4])}
df=pd.DataFrame(data)
print(df)

"""# Sorting the dataframe"""

import pandas as pd
data = {'Name' : ['name1', 'name2', 'name3'], 'Age' : [20, 21, 22]}
df = pd.DataFrame(data)
print("\nDataset before sorting :\n", df)
d_sort1 = df.sort_values(by='Name')
print("\nDataset after sorted by Name :\n", d_sort1)
d_sort2 = df.sort_values(by='Age')
print("\nDataset after sorted by Age :\n", d_sort2)

"""# Manipulation of data frame"""

print("Selection of column")
import pandas as pd
data = {'ONE' : pd.Series([10, 20, 30, 40], index=[1, 2, 3, 4]),
'TWO' : pd.Series([50, 60, 70, 80], index=[1, 2, 3, 4])}
df = pd.DataFrame(data)
print("------------------------")
print(df)
print("------------------------")
print("Selecting row ONE")
print(df['ONE'])
print("------------------------")
print("Selecting row TWO")
print(df['TWO'])
print("------------------------")

print("Addition of column")
import pandas as pd
data = {'ONE' : pd.Series([10, 20, 30, 40], index=[1, 2, 3, 4]),
'TWO' : pd.Series([50, 60, 70, 80], index=[1, 2, 3, 4])}
df = pd.DataFrame(data)
print("------------------------")
print("Data Frame before adding a new column")
print(df)
print("------------------------")
df['THREE'] = pd.Series([90, 100, 110, 120], index=[1, 2, 3, 4])
print("Data Frame after adding a new column\n", df)
print("------------------------")

print("Deletion of column")
import pandas as pd
data = {'ONE' : pd.Series([0, 1, 2, 3], index=[1, 2, 3, 4]),
'TWO' : pd.Series([4, 5, 6, 7], index=[1, 2, 3, 4])}
print("-----------------------")
df = pd.DataFrame(data)
print("Original DataFrame :\n", df)
print("-----------------------")
df.drop(['ONE'],axis=1) #or df.drop(df.columns[2],axis=1,inplace=True) or df.drop(df.loc[:,’name’:’mobilenumber’],axis=1,inplace=True)ordel df['ONE'] or df.pop(‘ONE’)
print("DataFrame after deleting a column :\n", df)
print("-----------------------")

print("Selection of rows")
import pandas as pd
data = {'ONE' : pd.Series([0, 1, 2, 3], index=['a', 'b', 'c', 'd']),
'TWO' : pd.Series([4, 5, 6, 7], index=['a', 'b', 'c', 'd'])}
print("-----------------------")
df = pd.DataFrame(data)
print("DataFrame :\n", df)
print("-----------------------")
print("row 'c' :")
print(df.loc['c'])
print("-----------------------")

print("Addition of rows")
import pandas as pd
df1 = pd.DataFrame([[1, 2], [3, 4]], columns = ['a', 'b'])
df2 = pd.DataFrame([[5, 6], [7, 8]], columns = ['a', 'b'])
print("---------------------")
print("df1 :")
print(df1)
print("---------------------")
print("df2 :")
print(df2)
print("---------------------")
print("df1 + df2 :")
df1 = pd.concat([df1,df2], ignore_index=True)
print(df1)

print("Deletion of rows")
import pandas as pd
df = pd.DataFrame([[1, 2], [3, 4]], columns = ['a', 'b'])
print("DataFrame :")
print(df)
df = df.drop(0)
print("DataFrame after deleting the row 0 :")
print(df)
print(df)
